services:
  - type: web
    name: store_browser_service
    env: docker
    repo: https://github.com/OmarGit99/Store_Browser/mern-scraper
    branch: main
    dockerfilePath: Dockerfile
    buildCommand: ""
    startCommand: "node server.js"
